# publish to pypi on github release (tagged as vX.Y.Z)
name: release_publish
on:
  # workflow_dispatch:
  release:
    types: [published]
jobs:
  pypi_publish:
    name: Deploy to pypi
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Pixi setup
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.41.4
          cache: false
          run-install: false

      - name: Build with pixi env
        run: pixi run pypi-build

      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
